### ISSUE TITLE
unable to import the Extractors

### ISSUE THREAD

**Issue by patrisilva** [joe-speedboat/graylog.contentpack#1]
I am new into Graylog, I was able to upload the file v3.x_LinuxCentos7ContentPack.json, but not the file v3.x_LinuxCentos7Extractors.json, I get this error:

Could not import content pack
Error importing content pack, please ensure it is a valid JSON file. Check your Graylog logs for more information.<br /><small>Unable to map property extractors. Known properties include: entities, rev, summary, vendor, inputs, lookup_tables, name, requires, url, outputs, streams, lookup_data_adapters, lookup_caches, _id, grok_patterns, description, category, dashboards, parameters, v, id</small>

Can you help me?

**Comment by joe-speedboat** [comment]
Hi 
Extractors have to be imported in extractors menu (near input menu)   
https://docs.graylog.org/en/3.0/pages/extractors.html   

ContentPacks have to be imported in content packs (contain input, extractors, ...)   
https://docs.graylog.org/en/3.0/pages/content_packs.html   

BR Chris

**Comment by patrisilva** [comment]
Thanks Chris, all working now.
Very kind of you.
